#ifndef HAL_TYPES_H
#define HAL_TYPES_H

typedef enum eHALReturnValue
{
    eRETURN_SUCCESS,
    eRETURN_INVALID_DEVICE,
    eRETURN_INVALID_PARAMETER,
    eRETURN_NULL_PARAMETER,
    eRETURN_DEVICE_ERROR

} eHALReturnValue;

#endif
